name: Deploy-test

on: 
    # push: 
        # branches: [ main ]
    
    workflow_dispatch: 

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            # ///////--------------------------------------------------------- PIPELINE INITIALIZATION /////////
            - name: Checkout code "Clone repository"
              uses: actions/checkout@v2
        
            - name: Install dependencies
              run: |
                npm ci
        
            # ///////--------------------------------------------------------- CODE-QUALITY REVIEW /////////
            - name: Static Analysis
              run: |
                echo "-->> All code OK. <<--"
        
            - name: Run Test
              run: |
                echo "-->> All tests PASSED. <<--"
        
            - name: Run Integration Test
              run: |
                echo "-->> All Integration Tests PASSED. <<--"
        
            - name: Run Visual Test
              run: |
                echo "-->> All Visual Tests PASSED. <<--"
        
            - name: Check Mandatory Modules
              run: |
                echo "-->> All Mandatory Modules CHECKED. <<--"
        
            # ///////--------------------------------------------------------- BUILD /////////
            - name: Build project "Build Artifact"
              run: |
                export NODE_OPTIONS=--openssl-legacy-provider
                npm run build
        
            # ///////--------------------------------------------------------- POST-BUILD REVIEW /////////
            - name: Run E2E Tests
              run: |
                echo "-->> All E2E Tests PASSED. <<--"
        
            - name: Check Performance
              run: |
                echo "-->> All Performance Tests are OK. <<--"
        
            #  PRE-DEPLOYMENT
            - name: Install AWS CLI
              run: |
                sudo apt-get update
                sudo apt-get install -y awscli
        
            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v2
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: us-east-1
        
            - name: Save Artifact
              run: |
                echo "-->> Artifact Saved. <<--"

            # ///////--------------------------------------------------------- DEPLOYMENT /////////
            - name: Sync files to S3
              run: |
                npm run deploy
